# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
    - main
  tags:
    include:
    - v*

jobs:
- job:  Build_Deploy_Win_x64
  pool:
    vmImage: windows-2019

  container: 
    image: oxidocker.azurecr.io/oxiwinbuild:99
    endpoint: Docker Registry

  variables:
    - name: oxiSourceDir
      value: $(Build.Repository.LocalPath)
    - name: oxiBuildDir
      value: $(Pipeline.Workspace)/build
    - name: oxiOutputName
      value: OXI-Desktop

  steps:
  - checkout: self
    lfs: true
    submodules: recursive
    displayName: Checkout Repository Recursively

  - script: mkdir build
    workingDirectory: $(Pipeline.Workspace)
    displayName: Create build directory

  - script: >
      C:/Qt/Tools/CMake_64/bin/cmake.exe
      -S $(oxiSourceDir)
      -B $(oxiBuildDir)
      "-DCMAKE_GENERATOR:STRING=Ninja"
      "-DCMAKE_BUILD_TYPE:STRING=Release"
      "-DCMAKE_PROJECT_INCLUDE_BEFORE:FILEPATH=C:/Qt/Tools/QtCreator/share/qtcreator/package-manager/auto-setup.cmake"
      "-DQT_QMAKE_EXECUTABLE:STRING=C:/Qt/6.2.4/mingw_64/bin/qmake.exe"
      "-DCMAKE_PREFIX_PATH:STRING=C:/Qt/6.2.4/mingw_64"
      "-DCMAKE_C_COMPILER:STRING=C:/Qt/Tools/mingw1120_64/bin/gcc.exe"
      "-DCMAKE_CXX_COMPILER:STRING=C:/Qt/Tools/mingw1120_64/bin/g++.exe"
    displayName: Create CMake cache

  - script: C:/Qt/Tools/CMake_64/bin/cmake.exe --build $(oxiBuildDir) --target all
    displayName: Build

  - script: mkdir deploy
    workingDirectory: $(oxiBuildDir)/apps/oxi_desktop
    displayName: Create deploy directory

  - script: |
      cp ../*.exe .
      cp ../*.dll .
      ls .
      echo %PATH%
      C:/Qt/6.2.4/mingw_64/bin/windeployqt.exe --no-translations --compiler-runtime $(oxiOutputName)
    workingDirectory: $(oxiBuildDir)/apps/oxi_desktop/deploy
    displayName: Create windows deployable

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(oxiBuildDir)/apps/oxi_desktop/deploy'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(oxiOutputName)_Win_x64.zip'
      replaceExistingArchive: true
    displayName: Copy archive to artifact staging directory

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: drop
      publishLocation: Container
    displayName: Publish artifact

- job:  Build_Deploy_MacOS
  pool:
    vmImage: macOS-10.15

  variables:
    - name: oxiSourceDir
      value: $(Build.Repository.LocalPath)
    - name: oxiBuildDir
      value: $(Pipeline.Workspace)/build

  steps:
  - checkout: self
    lfs: true
    submodules: recursive
    displayName: Checkout Repository Recursively

  - script: python3 -m pip install aqtinstall
    displayName: Pip Install aqtinstall

  - script: >
      sudo aqt install-qt --outputdir /opt/qt mac desktop 6.2.4 clang_64
      && sudo aqt install-tool --outputdir /opt/qt mac desktop tools_cmake
      && sudo aqt install-tool --outputdir /opt/qt mac desktop tools_ninja
      && sudo aqt install-tool --outputdir /opt/qt mac desktop tools_qtcreator
    displayName: Install Qt

  - script: mkdir build
    workingDirectory: $(Pipeline.Workspace)
    displayName: Create build directory

  - script: |
      echo '##vso[task.setvariable variable=path]$(PATH):/opt/qt/Tools/Ninja'
    displayName: Append Ninja to path

  - script: >
      /opt/qt/Tools/CMake/CMake.app/Contents/bin/cmake
      -S $(oxiSourceDir)
      -B $(oxiBuildDir)
      -DCMAKE_GENERATOR:STRING=Ninja 
      -DCMAKE_BUILD_TYPE:STRING=Release 
      '-DCMAKE_PROJECT_INCLUDE_BEFORE:FILEPATH=/opt/qt/Qt Creator.app/Contents/Resources/package-manager/auto-setup.cmake'
      -DQT_QMAKE_EXECUTABLE:FILEPATH=/opt/qt/6.2.4/macos/bin/qmake 
      -DCMAKE_PREFIX_PATH:PATH=/opt/qt/6.2.4/macos 
      -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang 
      -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++
    workingDirectory: $(oxiBuildDir)
    displayName: Build CMake Cache

  - script: /opt/qt/Tools/CMake/CMake.app/Contents/bin/cmake --build $(oxiBuildDir) --target all
    workingDirectory: $(oxiBuildDir)
    displayName: Build

  - script: mkdir deploy && cp -r ./$(oxiOutputName).app ./deploy
    workingDirectory: $(oxiBuildDir)/apps/oxi_desktop

  - script: /opt/qt/6.2.4/macos/bin/macdeployqt $(oxiOutputName).app -always-overwrite -dmg
    workingDirectory: $(oxiBuildDir)/apps/oxi_desktop/deploy
    displayName: Create Mac Deployable

  - script: mv $(oxiOutputName).dmg $(oxiOutputName)_MacOS.dmg
    workingDirectory: $(oxiBuildDir)/apps/oxi_desktop/deploy

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(oxiBuildDir)/apps/oxi_desktop/deploy'
      Contents: '$(oxiOutputName)_MacOS.dmg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: Copy Files to Staging Area

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: Publish Artifacts

- job: GitHub_Release
  pool:
    vmImage: windows-2019

  dependsOn:
    - Build_Deploy_Winx64
    - Build_Deploy_MacOS

  steps:
  - checkout: none

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      targetPath: '$(Pipeline.Workspace)'

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'GitHub OXI-Desktop'
      repositoryName: 'OXI-Instruments/OXI-Desktop'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      tagPattern: 'v*.*.*'
      title: 'OXI-Desktop $(Build.SourceBranchName)'
      releaseNotesSource: 'inline'
      releaseNotesInline: 'Build Pipeline $(Build.BuildNumber) based on $(Build.SourceVersion)'
      assets: '$(Pipeline.Workspace)/*'
      addChangeLog: false
